object Versions {
    const val gradlePlugin = "7.4.2"
    const val kotlinAndroid = "1.8.0"
    const val coreKtx = "1.7.0"
    const val appcompat = "1.6.1"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val junit = "4.13.2"
    const val androidJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val hilt = "2.44"
    const val retrofit = "2.9.0"
    const val okhttpLoggingInterceptor = "4.10.0"
    const val coroutines = "1.6.4"
    const val lifecyclewRuntime = "2.6.1"
}